name = "team-limit-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[env.dev]
name = "team-limit-worker-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "app_db_dev"
database_id = "16465f10-0ac7-4956-986e-9ccd2c0521ee"

[env.prod]
name = "team-limit-worker"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "app_db"
database_id = "b38cb72c-9056-43dc-9ce4-d07d7c8afa59"
